const { tiles } = require('../../utils/constants');

module.exports = {
  layout: [
    tiles.GROUND.repeat(99) + tiles.PORTAL.repeat(2) + tiles.GROUND.repeat(99),
    tiles.GROUND.repeat(200),
    tiles.GROUND.repeat(200),
    tiles.GROUND.repeat(200),
    tiles.GROUND.repeat(200),
    tiles.GROUND.repeat(200),
    tiles.GROUND.repeat(200),
    tiles.GROUND.repeat(200),
    tiles.GROUND.repeat(200),
    tiles.GROUND.repeat(200),
    tiles.GROUND.repeat(200),
    tiles.GROUND.repeat(200),
    tiles.GROUND.repeat(200),
    tiles.GROUND.repeat(200),
    tiles.GROUND.repeat(200),
    tiles.GROUND.repeat(200),
    tiles.GROUND.repeat(200),
    tiles.GROUND.repeat(200),
    tiles.GROUND.repeat(200),
    tiles.GROUND.repeat(200),
    tiles.GROUND.repeat(200),
    tiles.GROUND.repeat(200),
    tiles.GROUND.repeat(200),
    tiles.GROUND.repeat(200),
    tiles.GROUND.repeat(200),
    tiles.GROUND.repeat(200),
    tiles.GROUND.repeat(200),
    tiles.WALL.repeat(98) + tiles.GROUND.repeat(4) + tiles.WALL.repeat(98),
    tiles.WALL.repeat(98) + tiles.GROUND.repeat(4) + tiles.WALL.repeat(98),
    tiles.WALL.repeat(98) + tiles.GROUND.repeat(4) + tiles.WALL.repeat(98),
    tiles.WALL.repeat(98) + tiles.GROUND.repeat(4) + tiles.WALL.repeat(98),
    tiles.WALL.repeat(98) + tiles.GROUND.repeat(4) + tiles.WALL.repeat(98),
    tiles.WALL.repeat(98) + tiles.GROUND.repeat(4) + tiles.WALL.repeat(98),
    tiles.WALL.repeat(98) + tiles.GROUND.repeat(4) + tiles.WALL.repeat(98),
    tiles.WALL.repeat(98) + tiles.GROUND.repeat(4) + tiles.WALL.repeat(98),
    tiles.WALL.repeat(98) + tiles.GROUND.repeat(4) + tiles.WALL.repeat(98),
    tiles.WALL.repeat(98) + tiles.GROUND.repeat(4) + tiles.WALL.repeat(98),
    tiles.WALL.repeat(98) + tiles.GROUND.repeat(4) + tiles.WALL.repeat(98),
    tiles.WALL.repeat(98) + tiles.GROUND.repeat(4) + tiles.WALL.repeat(98),
    tiles.WALL.repeat(98) + tiles.GROUND.repeat(4) + tiles.WALL.repeat(98),
    tiles.WALL.repeat(98) + tiles.GROUND.repeat(4) + tiles.WALL.repeat(98),
    tiles.WALL.repeat(98) + tiles.GROUND.repeat(4) + tiles.WALL.repeat(98),
    tiles.WALL.repeat(98) + tiles.GROUND.repeat(4) + tiles.WALL.repeat(98),
    tiles.WALL.repeat(98) + tiles.GROUND.repeat(4) + tiles.WALL.repeat(98),
    tiles.WALL.repeat(98) + tiles.GROUND.repeat(4) + tiles.WALL.repeat(98),
    tiles.WALL.repeat(98) + tiles.GROUND.repeat(4) + tiles.WALL.repeat(98),
    tiles.WALL.repeat(98) + tiles.GROUND.repeat(4) + tiles.WALL.repeat(98),
    tiles.WALL.repeat(98) + tiles.GROUND.repeat(4) + tiles.WALL.repeat(98),
    tiles.WALL.repeat(98) + tiles.GROUND.repeat(4) + tiles.WALL.repeat(98),
    tiles.WALL.repeat(98) + tiles.GROUND.repeat(4) + tiles.WALL.repeat(98),
    tiles.WALL.repeat(98) + tiles.GROUND.repeat(4) + tiles.WALL.repeat(98),
    tiles.WALL.repeat(98) + tiles.GROUND.repeat(4) + tiles.WALL.repeat(98),
    tiles.WALL.repeat(98) + tiles.GROUND.repeat(4) + tiles.WALL.repeat(98),
    tiles.WALL.repeat(98) + tiles.GROUND.repeat(4) + tiles.WALL.repeat(98),
    tiles.WALL.repeat(98) + tiles.GROUND.repeat(4) + tiles.WALL.repeat(98),
    tiles.WALL.repeat(98) + tiles.GROUND.repeat(4) + tiles.WALL.repeat(98),
    tiles.WALL.repeat(98) + tiles.GROUND.repeat(4) + tiles.WALL.repeat(98),
    tiles.WALL.repeat(98) + tiles.GROUND.repeat(4) + tiles.WALL.repeat(98),
    tiles.WALL.repeat(98) + tiles.GROUND.repeat(4) + tiles.WALL.repeat(98),
    tiles.WALL.repeat(98) + tiles.GROUND.repeat(4) + tiles.WALL.repeat(98),
    tiles.WALL.repeat(98) + tiles.GROUND.repeat(4) + tiles.WALL.repeat(98),
    tiles.WALL.repeat(98) + tiles.GROUND.repeat(4) + tiles.WALL.repeat(98),
    tiles.WALL.repeat(98) + tiles.GROUND.repeat(4) + tiles.WALL.repeat(98),
    tiles.WALL.repeat(98) + tiles.GROUND.repeat(4) + tiles.WALL.repeat(98),
    tiles.WALL.repeat(98) + tiles.GROUND.repeat(4) + tiles.WALL.repeat(98),
    tiles.WALL.repeat(98) + tiles.GROUND.repeat(4) + tiles.WALL.repeat(98),
    tiles.WALL.repeat(98) + tiles.GROUND.repeat(4) + tiles.WALL.repeat(98),
    tiles.WALL.repeat(98) + tiles.GROUND.repeat(4) + tiles.WALL.repeat(98),
    tiles.WALL.repeat(98) + tiles.GROUND.repeat(4) + tiles.WALL.repeat(98),
    tiles.WALL.repeat(98) + tiles.GROUND.repeat(4) + tiles.WALL.repeat(98),
    tiles.WALL.repeat(98) + tiles.GROUND.repeat(4) + tiles.WALL.repeat(98),
    tiles.WALL.repeat(98) + tiles.GROUND.repeat(4) + tiles.WALL.repeat(98),
    tiles.WALL.repeat(98) + tiles.GROUND.repeat(4) + tiles.WALL.repeat(98),
    tiles.WALL.repeat(98) + tiles.GROUND.repeat(4) + tiles.WALL.repeat(98),
    tiles.WALL.repeat(98) + tiles.GROUND.repeat(4) + tiles.WALL.repeat(98),
    tiles.WALL.repeat(98) + tiles.GROUND.repeat(4) + tiles.WALL.repeat(98),
    tiles.WALL.repeat(98) + tiles.GROUND.repeat(4) + tiles.WALL.repeat(98),
    tiles.WALL.repeat(98) + tiles.GROUND.repeat(4) + tiles.WALL.repeat(98),
    tiles.WALL.repeat(98) + tiles.GROUND.repeat(4) + tiles.WALL.repeat(98),
    tiles.WALL.repeat(98) + tiles.GROUND.repeat(4) + tiles.WALL.repeat(98),
    tiles.WALL.repeat(98) + tiles.GROUND.repeat(4) + tiles.WALL.repeat(98),
    tiles.WALL.repeat(98) + tiles.GROUND.repeat(4) + tiles.WALL.repeat(98),
    tiles.WALL.repeat(98) + tiles.GROUND.repeat(4) + tiles.WALL.repeat(98),
    tiles.WALL.repeat(98) + tiles.GROUND.repeat(4) + tiles.WALL.repeat(98),
    tiles.WALL.repeat(98) + tiles.GROUND.repeat(4) + tiles.WALL.repeat(98),
    tiles.WALL.repeat(98) + tiles.GROUND.repeat(4) + tiles.WALL.repeat(98),
    tiles.WALL.repeat(98) + tiles.GROUND.repeat(4) + tiles.WALL.repeat(98),
    tiles.WALL.repeat(98) + tiles.GROUND.repeat(4) + tiles.WALL.repeat(98),
    tiles.WALL.repeat(98) + tiles.GROUND.repeat(4) + tiles.WALL.repeat(98),
    tiles.WALL.repeat(98) + tiles.GROUND.repeat(4) + tiles.WALL.repeat(98),
    tiles.WALL.repeat(98) + tiles.GROUND.repeat(4) + tiles.WALL.repeat(98),
    tiles.WALL.repeat(98) + tiles.GROUND.repeat(4) + tiles.WALL.repeat(98),
    tiles.WALL.repeat(98) + tiles.GROUND.repeat(4) + tiles.WALL.repeat(98),
    tiles.WALL.repeat(98) + tiles.GROUND.repeat(4) + tiles.WALL.repeat(98),
    tiles.WALL.repeat(98) + tiles.GROUND.repeat(4) + tiles.WALL.repeat(98),
    tiles.WALL.repeat(98) + tiles.GROUND.repeat(4) + tiles.WALL.repeat(98),
    tiles.WALL.repeat(98) + tiles.GROUND.repeat(4) + tiles.WALL.repeat(98),
    tiles.WALL.repeat(98) + tiles.GROUND.repeat(4) + tiles.WALL.repeat(98),
    tiles.WALL.repeat(98) + tiles.GROUND.repeat(4) + tiles.WALL.repeat(98),
    tiles.WALL.repeat(98) + tiles.GROUND.repeat(4) + tiles.WALL.repeat(98),
    tiles.WALL.repeat(98) + tiles.GROUND.repeat(4) + tiles.WALL.repeat(98),
    tiles.WALL.repeat(98) + tiles.GROUND.repeat(4) + tiles.WALL.repeat(98),
    tiles.WALL.repeat(98) + tiles.GROUND.repeat(4) + tiles.WALL.repeat(98),
    tiles.WALL.repeat(98) + tiles.GROUND.repeat(4) + tiles.WALL.repeat(98),
    tiles.WALL.repeat(98) + tiles.GROUND.repeat(4) + tiles.WALL.repeat(98),
    tiles.WALL.repeat(98) + tiles.GROUND.repeat(4) + tiles.WALL.repeat(98),
    tiles.WALL.repeat(98) + tiles.GROUND.repeat(4) + tiles.WALL.repeat(98),
    tiles.WALL.repeat(98) + tiles.GROUND.repeat(4) + tiles.WALL.repeat(98),
    tiles.WALL.repeat(98) + tiles.GROUND.repeat(4) + tiles.WALL.repeat(98),
    tiles.WALL.repeat(98) + tiles.GROUND.repeat(4) + tiles.WALL.repeat(98),
    tiles.WALL.repeat(98) + tiles.GROUND.repeat(4) + tiles.WALL.repeat(98),
    tiles.WALL.repeat(98) + tiles.GROUND.repeat(4) + tiles.WALL.repeat(98),
    tiles.WALL.repeat(98) + tiles.GROUND.repeat(4) + tiles.WALL.repeat(98),
    tiles.WALL.repeat(98) + tiles.GROUND.repeat(4) + tiles.WALL.repeat(98),
    tiles.WALL.repeat(98) + tiles.GROUND.repeat(4) + tiles.WALL.repeat(98),
    tiles.WALL.repeat(98) + tiles.GROUND.repeat(4) + tiles.WALL.repeat(98),
    tiles.WALL.repeat(98) + tiles.GROUND.repeat(4) + tiles.WALL.repeat(98),
    tiles.WALL.repeat(98) + tiles.GROUND.repeat(4) + tiles.WALL.repeat(98),
    tiles.WALL.repeat(98) + tiles.GROUND.repeat(4) + tiles.WALL.repeat(98),
    tiles.WALL.repeat(98) + tiles.GROUND.repeat(4) + tiles.WALL.repeat(98),
    tiles.WALL.repeat(98) + tiles.GROUND.repeat(4) + tiles.WALL.repeat(98),
    tiles.WALL.repeat(98) + tiles.GROUND.repeat(4) + tiles.WALL.repeat(98),
    tiles.WALL.repeat(98) + tiles.GROUND.repeat(4) + tiles.WALL.repeat(98),
    tiles.WALL.repeat(98) + tiles.GROUND.repeat(4) + tiles.WALL.repeat(98),
    tiles.WALL.repeat(98) + tiles.GROUND.repeat(4) + tiles.WALL.repeat(98),
    tiles.WALL.repeat(98) + tiles.GROUND.repeat(4) + tiles.WALL.repeat(98),
    tiles.WALL.repeat(98) + tiles.GROUND.repeat(4) + tiles.WALL.repeat(98),
    tiles.WALL.repeat(98) + tiles.GROUND.repeat(4) + tiles.WALL.repeat(98),
    tiles.WALL.repeat(98) + tiles.GROUND.repeat(4) + tiles.WALL.repeat(98),
    tiles.WALL.repeat(98) + tiles.GROUND.repeat(4) + tiles.WALL.repeat(98),
    tiles.WALL.repeat(98) + tiles.GROUND.repeat(4) + tiles.WALL.repeat(98),
    tiles.WALL.repeat(98) + tiles.GROUND.repeat(4) + tiles.WALL.repeat(98),
    tiles.WALL.repeat(98) + tiles.GROUND.repeat(4) + tiles.WALL.repeat(98),
    tiles.WALL.repeat(98) + tiles.GROUND.repeat(4) + tiles.WALL.repeat(98),
    tiles.WALL.repeat(98) + tiles.GROUND.repeat(4) + tiles.WALL.repeat(98),
    tiles.WALL.repeat(98) + tiles.GROUND.repeat(4) + tiles.WALL.repeat(98),
    tiles.WALL.repeat(98) + tiles.GROUND.repeat(4) + tiles.WALL.repeat(98),
    tiles.WALL.repeat(98) + tiles.GROUND.repeat(4) + tiles.WALL.repeat(98),
    tiles.WALL.repeat(98) + tiles.GROUND.repeat(4) + tiles.WALL.repeat(98),
    tiles.WALL.repeat(98) + tiles.GROUND.repeat(4) + tiles.WALL.repeat(98),
    tiles.WALL.repeat(98) + tiles.GROUND.repeat(4) + tiles.WALL.repeat(98),
    tiles.WALL.repeat(98) + tiles.GROUND.repeat(4) + tiles.WALL.repeat(98),
    tiles.WALL.repeat(98) + tiles.GROUND.repeat(4) + tiles.WALL.repeat(98),
    tiles.WALL.repeat(98) + tiles.GROUND.repeat(4) + tiles.WALL.repeat(98),
    tiles.WALL.repeat(98) + tiles.GROUND.repeat(4) + tiles.WALL.repeat(98),
    tiles.WALL.repeat(98) + tiles.GROUND.repeat(4) + tiles.WALL.repeat(98),
    tiles.WALL.repeat(98) + tiles.GROUND.repeat(4) + tiles.WALL.repeat(98),
    tiles.WALL.repeat(98) + tiles.GROUND.repeat(4) + tiles.WALL.repeat(98),
    tiles.WALL.repeat(98) + tiles.GROUND.repeat(4) + tiles.WALL.repeat(98),
    tiles.WALL.repeat(98) + tiles.GROUND.repeat(4) + tiles.WALL.repeat(98),
    tiles.WALL.repeat(98) + tiles.GROUND.repeat(4) + tiles.WALL.repeat(98),
    tiles.WALL.repeat(98) + tiles.GROUND.repeat(4) + tiles.WALL.repeat(98),
    tiles.WALL.repeat(98) + tiles.GROUND.repeat(4) + tiles.WALL.repeat(98),
    tiles.WALL.repeat(98) + tiles.GROUND.repeat(4) + tiles.WALL.repeat(98),
    tiles.WALL.repeat(98) + tiles.GROUND.repeat(4) + tiles.WALL.repeat(98),
    tiles.WALL.repeat(98) + tiles.GROUND.repeat(4) + tiles.WALL.repeat(98),
    tiles.WALL.repeat(98) + tiles.GROUND.repeat(4) + tiles.WALL.repeat(98),
    tiles.WALL.repeat(98) + tiles.GROUND.repeat(4) + tiles.WALL.repeat(98),
    tiles.WALL.repeat(98) + tiles.GROUND.repeat(4) + tiles.WALL.repeat(98),
    tiles.WALL.repeat(98) + tiles.GROUND.repeat(4) + tiles.WALL.repeat(98),
    tiles.WALL.repeat(98) + tiles.GROUND.repeat(4) + tiles.WALL.repeat(98),
    tiles.WALL.repeat(98) + tiles.GROUND.repeat(4) + tiles.WALL.repeat(98),
    tiles.WALL.repeat(98) + tiles.GROUND.repeat(4) + tiles.WALL.repeat(98),
    tiles.WALL.repeat(98) + tiles.GROUND.repeat(4) + tiles.WALL.repeat(98),
    tiles.WALL.repeat(98) + tiles.GROUND.repeat(4) + tiles.WALL.repeat(98),
    tiles.WALL.repeat(98) + tiles.GROUND.repeat(4) + tiles.WALL.repeat(98),
    tiles.WALL.repeat(98) + tiles.GROUND.repeat(4) + tiles.WALL.repeat(98),
    tiles.WALL.repeat(98) + tiles.GROUND.repeat(4) + tiles.WALL.repeat(98),
    tiles.WALL.repeat(98) + tiles.GROUND.repeat(4) + tiles.WALL.repeat(98),
    tiles.WALL.repeat(98) + tiles.GROUND.repeat(4) + tiles.WALL.repeat(98),
    tiles.WALL.repeat(98) + tiles.GROUND.repeat(4) + tiles.WALL.repeat(98),
    tiles.WALL.repeat(98) + tiles.GROUND.repeat(4) + tiles.WALL.repeat(98),
    tiles.WALL.repeat(98) + tiles.GROUND.repeat(4) + tiles.WALL.repeat(98),
    tiles.WALL.repeat(98) + tiles.GROUND.repeat(4) + tiles.WALL.repeat(98),
    tiles.WALL.repeat(98) + tiles.GROUND.repeat(4) + tiles.WALL.repeat(98),
    tiles.GROUND.repeat(200),
    tiles.GROUND.repeat(200),
    tiles.GROUND.repeat(200),
    tiles.GROUND.repeat(200),
    tiles.GROUND.repeat(200),
    tiles.GROUND.repeat(200),
    tiles.GROUND.repeat(200),
    tiles.GROUND.repeat(200),
    tiles.GROUND.repeat(200),
    tiles.GROUND.repeat(200),
    tiles.GROUND.repeat(200),
    tiles.GROUND.repeat(200),
    tiles.GROUND.repeat(200),
    tiles.GROUND.repeat(200),
    tiles.GROUND.repeat(200),
    tiles.GROUND.repeat(200),
    tiles.GROUND.repeat(200),
    tiles.GROUND.repeat(200),
    tiles.GROUND.repeat(200),
    tiles.GROUND.repeat(200),
    tiles.GROUND.repeat(200),
    tiles.GROUND.repeat(200),
    tiles.GROUND.repeat(200),
    tiles.GROUND.repeat(200),
    tiles.GROUND.repeat(99) + tiles.PORTAL.repeat(2) + tiles.GROUND.repeat(99),
  ],
  metadata: {
    portals: [
      {
        position: {
          x: 0,
          y: 4,
        },
      },
      {
        position: {
          x: 9,
          y: 4,
        },
      },
    ],
    monsters: [],
    adventurers: [],
  },
};
