const { tiles } = require('../../utils/constants');

module.exports = {
  layout: [
    tiles.GROUND.repeat(49) + tiles.PORTAL.repeat(2) + tiles.GROUND.repeat(49),
    tiles.GROUND.repeat(100),
    tiles.GROUND.repeat(100),
    tiles.GROUND.repeat(100),
    tiles.GROUND.repeat(100),
    tiles.GROUND.repeat(100),
    tiles.GROUND.repeat(100),
    tiles.GROUND.repeat(100),
    tiles.GROUND.repeat(100),
    tiles.GROUND.repeat(100),
    tiles.GROUND.repeat(100),
    tiles.GROUND.repeat(100),
    tiles.GROUND.repeat(100),
    tiles.GROUND.repeat(100),
    tiles.GROUND.repeat(100),
    tiles.GROUND.repeat(100),
    tiles.GROUND.repeat(100),
    tiles.GROUND.repeat(100),
    tiles.GROUND.repeat(100),
    tiles.GROUND.repeat(100),
    tiles.GROUND.repeat(100),
    tiles.GROUND.repeat(100),
    tiles.GROUND.repeat(100),
    tiles.GROUND.repeat(100),
    tiles.GROUND.repeat(100),
    tiles.GROUND.repeat(100),
    tiles.GROUND.repeat(100),
    tiles.WALL.repeat(48) + tiles.GROUND.repeat(4) + tiles.WALL.repeat(48),
    tiles.WALL.repeat(48) + tiles.GROUND.repeat(4) + tiles.WALL.repeat(48),
    tiles.WALL.repeat(48) + tiles.GROUND.repeat(4) + tiles.WALL.repeat(48),
    tiles.WALL.repeat(48) + tiles.GROUND.repeat(4) + tiles.WALL.repeat(48),
    tiles.WALL.repeat(48) + tiles.GROUND.repeat(4) + tiles.WALL.repeat(48),
    tiles.WALL.repeat(48) + tiles.GROUND.repeat(4) + tiles.WALL.repeat(48),
    tiles.WALL.repeat(48) + tiles.GROUND.repeat(4) + tiles.WALL.repeat(48),
    tiles.WALL.repeat(48) + tiles.GROUND.repeat(4) + tiles.WALL.repeat(48),
    tiles.WALL.repeat(48) + tiles.GROUND.repeat(4) + tiles.WALL.repeat(48),
    tiles.WALL.repeat(48) + tiles.GROUND.repeat(4) + tiles.WALL.repeat(48),
    tiles.WALL.repeat(48) + tiles.GROUND.repeat(4) + tiles.WALL.repeat(48),
    tiles.WALL.repeat(48) + tiles.GROUND.repeat(4) + tiles.WALL.repeat(48),
    tiles.WALL.repeat(48) + tiles.GROUND.repeat(4) + tiles.WALL.repeat(48),
    tiles.WALL.repeat(48) + tiles.GROUND.repeat(4) + tiles.WALL.repeat(48),
    tiles.WALL.repeat(48) + tiles.GROUND.repeat(4) + tiles.WALL.repeat(48),
    tiles.WALL.repeat(48) + tiles.GROUND.repeat(4) + tiles.WALL.repeat(48),
    tiles.WALL.repeat(48) + tiles.GROUND.repeat(4) + tiles.WALL.repeat(48),
    tiles.WALL.repeat(48) + tiles.GROUND.repeat(4) + tiles.WALL.repeat(48),
    tiles.WALL.repeat(48) + tiles.GROUND.repeat(4) + tiles.WALL.repeat(48),
    tiles.WALL.repeat(48) + tiles.GROUND.repeat(4) + tiles.WALL.repeat(48),
    tiles.WALL.repeat(48) + tiles.GROUND.repeat(4) + tiles.WALL.repeat(48),
    tiles.WALL.repeat(48) + tiles.GROUND.repeat(4) + tiles.WALL.repeat(48),
    tiles.WALL.repeat(48) + tiles.GROUND.repeat(4) + tiles.WALL.repeat(48),
    tiles.WALL.repeat(48) + tiles.GROUND.repeat(4) + tiles.WALL.repeat(48),
    tiles.WALL.repeat(48) + tiles.GROUND.repeat(4) + tiles.WALL.repeat(48),
    tiles.WALL.repeat(48) + tiles.GROUND.repeat(4) + tiles.WALL.repeat(48),
    tiles.WALL.repeat(48) + tiles.GROUND.repeat(4) + tiles.WALL.repeat(48),
    tiles.WALL.repeat(48) + tiles.GROUND.repeat(4) + tiles.WALL.repeat(48),
    tiles.WALL.repeat(48) + tiles.GROUND.repeat(4) + tiles.WALL.repeat(48),
    tiles.WALL.repeat(48) + tiles.GROUND.repeat(4) + tiles.WALL.repeat(48),
    tiles.WALL.repeat(48) + tiles.GROUND.repeat(4) + tiles.WALL.repeat(48),
    tiles.WALL.repeat(48) + tiles.GROUND.repeat(4) + tiles.WALL.repeat(48),
    tiles.WALL.repeat(48) + tiles.GROUND.repeat(4) + tiles.WALL.repeat(48),
    tiles.WALL.repeat(48) + tiles.GROUND.repeat(4) + tiles.WALL.repeat(48),
    tiles.WALL.repeat(48) + tiles.GROUND.repeat(4) + tiles.WALL.repeat(48),
    tiles.WALL.repeat(48) + tiles.GROUND.repeat(4) + tiles.WALL.repeat(48),
    tiles.WALL.repeat(48) + tiles.GROUND.repeat(4) + tiles.WALL.repeat(48),
    tiles.WALL.repeat(48) + tiles.GROUND.repeat(4) + tiles.WALL.repeat(48),
    tiles.WALL.repeat(48) + tiles.GROUND.repeat(4) + tiles.WALL.repeat(48),
    tiles.WALL.repeat(48) + tiles.GROUND.repeat(4) + tiles.WALL.repeat(48),
    tiles.WALL.repeat(48) + tiles.GROUND.repeat(4) + tiles.WALL.repeat(48),
    tiles.WALL.repeat(48) + tiles.GROUND.repeat(4) + tiles.WALL.repeat(48),
    tiles.WALL.repeat(48) + tiles.GROUND.repeat(4) + tiles.WALL.repeat(48),
    tiles.WALL.repeat(48) + tiles.GROUND.repeat(4) + tiles.WALL.repeat(48),
    tiles.WALL.repeat(48) + tiles.GROUND.repeat(4) + tiles.WALL.repeat(48),
    tiles.WALL.repeat(48) + tiles.GROUND.repeat(4) + tiles.WALL.repeat(48),
    tiles.WALL.repeat(48) + tiles.GROUND.repeat(4) + tiles.WALL.repeat(48),
    tiles.WALL.repeat(48) + tiles.GROUND.repeat(4) + tiles.WALL.repeat(48),
    tiles.GROUND.repeat(100),
    tiles.GROUND.repeat(100),
    tiles.GROUND.repeat(100),
    tiles.GROUND.repeat(100),
    tiles.GROUND.repeat(100),
    tiles.GROUND.repeat(100),
    tiles.GROUND.repeat(100),
    tiles.GROUND.repeat(100),
    tiles.GROUND.repeat(100),
    tiles.GROUND.repeat(100),
    tiles.GROUND.repeat(100),
    tiles.GROUND.repeat(100),
    tiles.GROUND.repeat(100),
    tiles.GROUND.repeat(100),
    tiles.GROUND.repeat(100),
    tiles.GROUND.repeat(100),
    tiles.GROUND.repeat(100),
    tiles.GROUND.repeat(100),
    tiles.GROUND.repeat(100),
    tiles.GROUND.repeat(100),
    tiles.GROUND.repeat(100),
    tiles.GROUND.repeat(100),
    tiles.GROUND.repeat(100),
    tiles.GROUND.repeat(100),
    tiles.GROUND.repeat(49) + tiles.PORTAL.repeat(2) + tiles.GROUND.repeat(49),
  ],
  metadata: {
    portals: [
      {
        position: {
          x: 0,
          y: 4,
        },
      },
      {
        position: {
          x: 9,
          y: 4,
        },
      },
    ],
    monsters: [],
    adventurers: [],
  },
};
