const { tiles } = require('../../constants');

module.exports = {
  layout: [
    tiles.GROUND.repeat(19) + tiles.PORTAL.repeat(2) + tiles.GROUND.repeat(19),
    tiles.GROUND.repeat(40),
    tiles.GROUND.repeat(40),
    tiles.GROUND.repeat(40),
    tiles.GROUND.repeat(40),
    tiles.GROUND.repeat(40),
    tiles.GROUND.repeat(40),
    tiles.GROUND.repeat(40),
    tiles.GROUND.repeat(40),
    tiles.GROUND.repeat(40),
    tiles.GROUND.repeat(40),
    tiles.GROUND.repeat(40),
    tiles.GROUND.repeat(40),
    tiles.WALL.repeat(18) + tiles.GROUND.repeat(4) + tiles.WALL.repeat(18),
    tiles.WALL.repeat(18) + tiles.GROUND.repeat(4) + tiles.WALL.repeat(18),
    tiles.WALL.repeat(18) + tiles.GROUND.repeat(4) + tiles.WALL.repeat(18),
    tiles.WALL.repeat(18) + tiles.GROUND.repeat(4) + tiles.WALL.repeat(18),
    tiles.WALL.repeat(18) + tiles.GROUND.repeat(4) + tiles.WALL.repeat(18),
    tiles.WALL.repeat(18) + tiles.GROUND.repeat(4) + tiles.WALL.repeat(18),
    tiles.WALL.repeat(18) + tiles.GROUND.repeat(4) + tiles.WALL.repeat(18),
    tiles.WALL.repeat(18) + tiles.GROUND.repeat(4) + tiles.WALL.repeat(18),
    tiles.WALL.repeat(18) + tiles.GROUND.repeat(4) + tiles.WALL.repeat(18),
    tiles.WALL.repeat(18) + tiles.GROUND.repeat(4) + tiles.WALL.repeat(18),
    tiles.WALL.repeat(18) + tiles.GROUND.repeat(4) + tiles.WALL.repeat(18),
    tiles.WALL.repeat(18) + tiles.GROUND.repeat(4) + tiles.WALL.repeat(18),
    tiles.WALL.repeat(18) + tiles.GROUND.repeat(4) + tiles.WALL.repeat(18),
    tiles.WALL.repeat(18) + tiles.GROUND.repeat(4) + tiles.WALL.repeat(18),
    tiles.GROUND.repeat(40),
    tiles.GROUND.repeat(40),
    tiles.GROUND.repeat(40),
    tiles.GROUND.repeat(40),
    tiles.GROUND.repeat(40),
    tiles.GROUND.repeat(40),
    tiles.GROUND.repeat(40),
    tiles.GROUND.repeat(40),
    tiles.GROUND.repeat(40),
    tiles.GROUND.repeat(40),
    tiles.GROUND.repeat(40),
    tiles.GROUND.repeat(40),
    tiles.GROUND.repeat(19) + tiles.PORTAL.repeat(2) + tiles.GROUND.repeat(19),
  ],
  metadata: {
    portals: [
      {
        position: {
          x: 0,
          y: 4,
        },
      },
      {
        position: {
          x: 9,
          y: 4,
        },
      },
    ],
  },
};
