const { tiles } = require('../../utils/constants');

module.exports = {
  layout: [
    tiles.GROUND.repeat(24) + tiles.PORTAL.repeat(2) + tiles.GROUND.repeat(24),
    tiles.GROUND.repeat(50),
    tiles.GROUND.repeat(50),
    tiles.GROUND.repeat(50),
    tiles.GROUND.repeat(50),
    tiles.GROUND.repeat(50),
    tiles.GROUND.repeat(50),
    tiles.GROUND.repeat(50),
    tiles.GROUND.repeat(50),
    tiles.GROUND.repeat(50),
    tiles.GROUND.repeat(50),
    tiles.GROUND.repeat(50),
    tiles.GROUND.repeat(50),
    tiles.GROUND.repeat(50),
    tiles.GROUND.repeat(50),
    tiles.GROUND.repeat(50),
    tiles.WALL.repeat(23) + tiles.GROUND.repeat(4) + tiles.WALL.repeat(23),
    tiles.WALL.repeat(23) + tiles.GROUND.repeat(4) + tiles.WALL.repeat(23),
    tiles.WALL.repeat(23) + tiles.GROUND.repeat(4) + tiles.WALL.repeat(23),
    tiles.WALL.repeat(23) + tiles.GROUND.repeat(4) + tiles.WALL.repeat(23),
    tiles.WALL.repeat(23) + tiles.GROUND.repeat(4) + tiles.WALL.repeat(23),
    tiles.WALL.repeat(23) + tiles.GROUND.repeat(4) + tiles.WALL.repeat(23),
    tiles.WALL.repeat(23) + tiles.GROUND.repeat(4) + tiles.WALL.repeat(23),
    tiles.WALL.repeat(23) + tiles.GROUND.repeat(4) + tiles.WALL.repeat(23),
    tiles.WALL.repeat(23) + tiles.GROUND.repeat(4) + tiles.WALL.repeat(23),
    tiles.WALL.repeat(23) + tiles.GROUND.repeat(4) + tiles.WALL.repeat(23),
    tiles.WALL.repeat(23) + tiles.GROUND.repeat(4) + tiles.WALL.repeat(23),
    tiles.WALL.repeat(23) + tiles.GROUND.repeat(4) + tiles.WALL.repeat(23),
    tiles.WALL.repeat(23) + tiles.GROUND.repeat(4) + tiles.WALL.repeat(23),
    tiles.WALL.repeat(23) + tiles.GROUND.repeat(4) + tiles.WALL.repeat(23),
    tiles.WALL.repeat(23) + tiles.GROUND.repeat(4) + tiles.WALL.repeat(23),
    tiles.WALL.repeat(23) + tiles.GROUND.repeat(4) + tiles.WALL.repeat(23),
    tiles.WALL.repeat(23) + tiles.GROUND.repeat(4) + tiles.WALL.repeat(23),
    tiles.WALL.repeat(23) + tiles.GROUND.repeat(4) + tiles.WALL.repeat(23),
    tiles.WALL.repeat(23) + tiles.GROUND.repeat(4) + tiles.WALL.repeat(23),
    tiles.WALL.repeat(23) + tiles.GROUND.repeat(4) + tiles.WALL.repeat(23),
    tiles.GROUND.repeat(50),
    tiles.GROUND.repeat(50),
    tiles.GROUND.repeat(50),
    tiles.GROUND.repeat(50),
    tiles.GROUND.repeat(50),
    tiles.GROUND.repeat(50),
    tiles.GROUND.repeat(50),
    tiles.GROUND.repeat(50),
    tiles.GROUND.repeat(50),
    tiles.GROUND.repeat(50),
    tiles.GROUND.repeat(50),
    tiles.GROUND.repeat(50),
    tiles.GROUND.repeat(50),
    tiles.GROUND.repeat(24) + tiles.PORTAL.repeat(2) + tiles.GROUND.repeat(24),
  ],
  metadata: {
    portals: [
      {
        position: {
          x: 0,
          y: 4,
        },
      },
      {
        position: {
          x: 9,
          y: 4,
        },
      },
    ],
    monsters: [],
    adventurers: [],
  },
};
