module.exports = {
  ACTIVE_MAPS: 'ACTIVE_MAPS',
  QUEUE_TO_CONNECT_ADVENTURERS: 'QUEUE_TO_CONNECT_ADVENTURERS',
  CONNECTED_ADVENTURERS: 'CONNECTED_ADVENTURERS',
  MAP_PREFIX: 'MAP-',
  ADVENTURER_PREFIX: 'ADVENTURER-',
  ADVENTURER_MANUAL_ACTIONS_PREFIX: 'ADVENTURER_MANUAL-',
  MONSTER_PREFIX: 'MONSTER-',
};
