const engine = require('./engine');

module.exports = {
  DEFAULT_SIGHT_RANGE: 6,
  DEFAULT_ATTACK_RANGE: 1,
  MOVEMENT_COOLDOWN: Math.floor(engine.TICK_RATE / 3),
  ATTACK_COOLDOWN: Math.floor(engine.TICK_RATE * 3),
  MOVEMENTS: ['UP', 'DOWN', 'LEFT', 'RIGHT'],
  UP: 'UP',
  DOWN: 'DOWN',
  LEFT: 'LEFT',
  RIGHT: 'RIGHT',
  DAMAGE_PERCENTAGE_VARIATION: 0.20,
  STRENGTH_MULTIPLIER_TO_ATTACK: 1.15,
  DEXTERITY_MULTIPLIER_TO_ATTACK: 0.15,
  INTELLIGENCE_MULTIPLIER_TO_MAGIC_ATTACK: 0.95,
  VITALITY_MULTIPLIER_TO_DEFENSE: 0.75,
  VITALITY_MULTIPLIER_TO_MAGIC_DEFENSE: 0.25,
  INTELLIGENCE_MULTIPLIER_TO_MAGIC_DEFENSE: 0.55,
  DEXTERITY_MULTIPLIER_TO_HIT: 0.75,
  AGILITY_MULTIPLIER_TO_FLEE: 0.5,
  VITALITY_INCREMENT_TO_HEALTH: 14,
  INTELLIGENCE_INCREMENT_TO_MANA: 7,
  EXPERIENCE_TABLE: {
    1: 100,
    2: 145,
    3: 210,
    4: 300,
    5: 420,
    6: 600,
    7: 850,
    8: 1200,
    9: 1600,
    10: 2100
  },
  POINTS_PER_LEVEL: 5
};
